/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: '006_ADC_Multple_Channels_with_DMA_Circular_Mode' 
 * Target:  '006_ADC_Multple_Channels_with_DMA_Circular_Mode' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H



#endif /* RTE_COMPONENTS_H */
