/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: '007_ADC_Multiple_Channels_Without_DMA' 
 * Target:  '007_ADC_Multiple_Channels_Without_DMA' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H



#endif /* RTE_COMPONENTS_H */
